# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2010 - 2025 Intel Corporation.

KERNEL_VERSION := $(shell echo $(KERNELRELEASE) | cut -d- -f1 | sed -r 's/([0-9]+\.[0-9]+).*/\1.0/g')

ccflags-y := -DDRIVER_VERSION_SUFFIX=\"${DRIVER_VERSION_SUFFIX}\"

ccflags-y += -I$(src)/../../../$(KERNEL_VERSION)/include-overrides

obj-$(CONFIG_VIDEO_AR0233) += ar0233.o
obj-$(CONFIG_VIDEO_AR0234) += ar0234.o
obj-$(CONFIG_VIDEO_AR0820) += ar0820.o
obj-$(CONFIG_VIDEO_AR0830) += ar0830.o
obj-$(CONFIG_VIDEO_ISX031) += isx031.o
obj-$(CONFIG_VIDEO_LT6911UXC) += lt6911uxc.o
obj-$(CONFIG_VIDEO_LT6911UXE) += lt6911uxe.o
obj-$(CONFIG_VIDEO_LT6911GXD) += lt6911gxd.o
obj-$(CONFIG_VIDEO_IMX415) += imx415.o

subdir-ccflags-y := -DDRIVER_VERSION_SUFFIX=\"${DRIVER_VERSION_SUFFIX}\"
obj-$(CONFIG_VIDEO_MAX9X) += max9x/
obj-$(CONFIG_VIDEO_IMX586) += imx586.o
obj-$(CONFIG_VIDEO_MAXIM_SERDES) += maxim-serdes/
obj-$(CONFIG_VIDEO_D4XX) += d4xx.o